import type { Metadata } from "next";
import Providers from "../providers";
import { getServerSession } from "next-auth";
import "../assets/css/global.css"
import authOptions from "../services/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://designs.hubtel.com/v4//assets/css/main.css"
          rel="stylesheet"
        />
        <link
          href="https://designs.hubtel.com/v4//assets/css/main.css?v=3"
          rel="stylesheet"
        />
      </head>

      <body>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
